trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'compile-code.sh'
    script: sudo apt-get install -qq -y tree
- task: Bash@3
  inputs: 
    filePath: 'tree.sh'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'code'
    ArtifactName: 'drop'
    publishLocation: 'Container'