# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'compile-code.sh'

- task: Install tree
  inputs:
    script: sudo apt-get install -qq -y tree

- task: Create fileindex
  inputs:
    script: cd code  
    find . -type d -exec tree -H . -o  '{}/index.html' \;
    cd ..

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'code'
    ArtifactName: 'drop'
    publishLocation: 'Container'
