# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'compile-code.sh'

- task: Create fileindex
  inputs:
    script:  find . -type d -exec tree -H ./code -o  '{}/index.html' \;

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'code'
    ArtifactName: 'drop'
    publishLocation: 'Container'
