# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'compile-code.sh'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'code'
    ArtifactName: 'drop'
    publishLocation: 'Container'
